name: Check dist

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: yarn

      - name: Install dependencies
        run: yarn install --check-files

      - name: Rebuild the dist directory
        run: yarn build

      - name: Compare the expected and actual dist directories
        run: |
          if [ "$(git diff --ignore-space-at-eol ./dist | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after the build. See the status below:"
            git diff
            exit 1
          fi
        id: diff

      # If inners of the dist directory were different than expected, upload the expected version as an artifact
      - name: Upload artifact
        if: ${{failure() && steps.diff.conclusion == 'failure'}}
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist
